/* Generated By:JavaCC: Do not edit this line. PQLParserConstants.java */
package sagex.phoenix.db;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int EQUALS = 9;
  /** RegularExpression Id. */
  int GREATERTHAN = 10;
  /** RegularExpression Id. */
  int LESSTHAN = 11;
  /** RegularExpression Id. */
  int NOTEQUAL = 12;
  /** RegularExpression Id. */
  int CONTAINS = 13;
  /** RegularExpression Id. */
  int IS_NOT_NULL = 14;
  /** RegularExpression Id. */
  int IS_NULL = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int QUOTED_STRING = 17;
  /** RegularExpression Id. */
  int SQUOTED_STRING = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"and\"",
    "\"or\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"<>\"",
    "\"contains\"",
    "\"is not\"",
    "\"is\"",
    "<STRING>",
    "<QUOTED_STRING>",
    "<SQUOTED_STRING>",
  };

}
