package sagex.phoenix.homecontrol.themostat.nest;

import java.io.IOException;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class FakeNestControl extends NestThermostatControl {
	public FakeNestControl() {
	}

	@Override
	protected JsonObject resolveNestData() throws IOException {
		JsonParser p = new JsonParser();

		return p.parse("{\r\n" + 
				"   \"tuneups\":{\r\n" + 
				"      \"02AA01AB501208GY\":{\r\n" + 
				"         \"$version\":-1,\r\n" + 
				"         \"$timestamp\":1\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"metadata\":{\r\n" + 
				"      \"02AA01AB501208GY\":{\r\n" + 
				"         \"$version\":-1,\r\n" + 
				"         \"$timestamp\":1356998400000,\r\n" + 
				"         \"last_ip\":\"127.0.0.1\",\r\n" + 
				"         \"last_connection\":1356998400000\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"track\":{\r\n" + 
				"      \"02AA01AB501208GY\":{\r\n" + 
				"         \"$version\":-209505229,\r\n" + 
				"         \"$timestamp\":1368395013481,\r\n" + 
				"         \"online\":true,\r\n" + 
				"         \"last_connection\":1368395013481,\r\n" + 
				"         \"last_ip\":\"99.248.231.247\"\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"user_settings\":{\r\n" + 
				"      \"323260\":{\r\n" + 
				"         \"$version\":1529756391,\r\n" + 
				"         \"$timestamp\":1368143985250,\r\n" + 
				"         \"email_verified\":true,\r\n" + 
				"         \"tos_accepted_version\":1319500800000,\r\n" + 
				"         \"receive_marketing_emails\":true,\r\n" + 
				"         \"receive_nest_emails\":true,\r\n" + 
				"         \"receive_support_emails\":true,\r\n" + 
				"         \"max_structures\":2,\r\n" + 
				"         \"max_thermostats\":10,\r\n" + 
				"         \"max_thermostats_per_structure\":10,\r\n" + 
				"         \"tos_minimum_version\":1319500800000,\r\n" + 
				"         \"tos_current_version\":1319500800000,\r\n" + 
				"         \"lang\":\"en_US\"\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"structure\":{\r\n" + 
				"      \"73f6fb70-b904-11e2-acbb-12313b0cf507\":{\r\n" + 
				"         \"$version\":-559764244,\r\n" + 
				"         \"$timestamp\":1368377491000,\r\n" + 
				"         \"away_timestamp\":1368377486,\r\n" + 
				"         \"away\":false,\r\n" + 
				"         \"touched_by\":{\r\n" + 
				"            \"touched_by\":5\r\n" + 
				"         },\r\n" + 
				"         \"dr_reminder_enabled\":true,\r\n" + 
				"         \"house_type\":\"family\",\r\n" + 
				"         \"postal_code\":\"N5Y5M4\",\r\n" + 
				"         \"num_thermostats\":\"1\",\r\n" + 
				"         \"renovation_date\":\"2000\",\r\n" + 
				"         \"country_code\":\"CA\",\r\n" + 
				"         \"structure_area\":232.258,\r\n" + 
				"         \"away_setter\":0,\r\n" + 
				"         \"measurement_scale\":\"imperial\",\r\n" + 
				"         \"user\":\"user.323260\",\r\n" + 
				"         \"devices\":[\r\n" + 
				"            \"device.02AA01AB501208GY\"\r\n" + 
				"         ]\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"demand_response\":{\r\n" + 
				"      \"02AA01AB501208GY\":{\r\n" + 
				"         \"$version\":-1,\r\n" + 
				"         \"$timestamp\":1\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"utility\":{\r\n" + 
				"      \"73f6fb70-b904-11e2-acbb-12313b0cf507\":{\r\n" + 
				"         \"$version\":-1,\r\n" + 
				"         \"$timestamp\":1\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"link\":{\r\n" + 
				"      \"02AA01AB501208GY\":{\r\n" + 
				"         \"$version\":-239757552,\r\n" + 
				"         \"$timestamp\":1368371408000,\r\n" + 
				"         \"structure\":\"structure.73f6fb70-b904-11e2-acbb-12313b0cf507\"\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"message_center\":{\r\n" + 
				"      \"323260\":{\r\n" + 
				"         \"$version\":-1,\r\n" + 
				"         \"$timestamp\":1325379661000,\r\n" + 
				"         \"messages\":[\r\n" + 
				"\r\n" + 
				"         ]\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"device\":{\r\n" + 
				"      \"02AA01AB501208GY\":{\r\n" + 
				"         \"$version\":-797772820,\r\n" + 
				"         \"$timestamp\":1368387773000,\r\n" + 
				"         \"heatpump_setback_active\":false,\r\n" + 
				"         \"touched_by\":{\r\n" + 
				"\r\n" + 
				"         },\r\n" + 
				"         \"emer_heat_enable\":false,\r\n" + 
				"         \"switch_system_off\":false,\r\n" + 
				"         \"local_ip\":\"192.168.1.111\",\r\n" + 
				"         \"away_temperature_high\":29.0,\r\n" + 
				"         \"y2_type\":\"unknown\",\r\n" + 
				"         \"temperature_lock_high_temp\":22.222,\r\n" + 
				"         \"cooling_source\":\"electric\",\r\n" + 
				"         \"leaf_threshold_cool\":25.55,\r\n" + 
				"         \"heater_source\":\"gas\",\r\n" + 
				"         \"fan_cooling_state\":false,\r\n" + 
				"         \"note_codes\":[\r\n" + 
				"\r\n" + 
				"         ],\r\n" + 
				"         \"compressor_lockout_leaf\":-17.8,\r\n" + 
				"         \"has_x3_heat\":false,\r\n" + 
				"         \"target_humidity_enabled\":false,\r\n" + 
				"         \"heat_x3_source\":\"gas\",\r\n" + 
				"         \"alt_heat_delivery\":\"forced-air\",\r\n" + 
				"         \"has_x2_heat\":false,\r\n" + 
				"         \"fan_mode\":\"auto\",\r\n" + 
				"         \"sunlight_correction_active\":false,\r\n" + 
				"         \"rssi\":67.0,\r\n" + 
				"         \"emer_heat_delivery\":\"forced-air\",\r\n" + 
				"         \"heatpump_savings\":\"off\",\r\n" + 
				"         \"pin_y2_description\":\"none\",\r\n" + 
				"         \"filter_reminder_level\":0,\r\n" + 
				"         \"filter_reminder_enabled\":false,\r\n" + 
				"         \"capability_level\":3.5,\r\n" + 
				"         \"schedule_learning_reset\":false,\r\n" + 
				"         \"has_x2_cool\":false,\r\n" + 
				"         \"hvac_pins\":\"W1,Y1,Rh,G\",\r\n" + 
				"         \"ob_orientation\":\"O\",\r\n" + 
				"         \"cooling_delivery\":\"unknown\",\r\n" + 
				"         \"range_enable\":true,\r\n" + 
				"         \"dual_fuel_breakpoint_override\":\"none\",\r\n" + 
				"         \"auto_away_enable\":true,\r\n" + 
				"         \"lower_safety_temp_enabled\":true,\r\n" + 
				"         \"has_fan\":true,\r\n" + 
				"         \"dehumidifier_state\":false,\r\n" + 
				"         \"emer_heat_source\":\"electric\",\r\n" + 
				"         \"nlclient_state\":\"\",\r\n" + 
				"         \"heatpump_ready\":false,\r\n" + 
				"         \"cooling_x2_delivery\":\"unknown\",\r\n" + 
				"         \"available_locales\":\"en_US,fr_CA,es_US\",\r\n" + 
				"         \"current_version\":\"3.5\",\r\n" + 
				"         \"learning_state\":\"steady\",\r\n" + 
				"         \"pin_ob_description\":\"none\",\r\n" + 
				"         \"pin_rh_description\":\"power\",\r\n" + 
				"         \"has_alt_heat\":false,\r\n" + 
				"         \"fan_duty_cycle\":3600,\r\n" + 
				"         \"pin_y1_description\":\"cool\",\r\n" + 
				"         \"humidifier_state\":false,\r\n" + 
				"         \"gear_threshold_high\":0.0,\r\n" + 
				"         \"backplate_serial_number\":\"02BA01AB50120NZU\",\r\n" + 
				"         \"has_x2_alt_heat\":false,\r\n" + 
				"         \"heat_x3_delivery\":\"forced-air\",\r\n" + 
				"         \"leaf_threshold_heat\":18.89,\r\n" + 
				"         \"has_emer_heat\":false,\r\n" + 
				"         \"learning_mode\":true,\r\n" + 
				"         \"leaf_learning\":\"ready\",\r\n" + 
				"         \"has_aux_heat\":false,\r\n" + 
				"         \"filter_changed_set_date\":0,\r\n" + 
				"         \"aux_heat_source\":\"electric\",\r\n" + 
				"         \"backplate_bsl_info\":\"BSL\",\r\n" + 
				"         \"sunlight_correction_ready\":false,\r\n" + 
				"         \"alt_heat_x2_source\":\"gas\",\r\n" + 
				"         \"pin_c_description\":\"none\",\r\n" + 
				"         \"humidifier_type\":\"unknown\",\r\n" + 
				"         \"pin_w2aux_description\":\"none\",\r\n" + 
				"         \"fan_timer_timeout\":0,\r\n" + 
				"         \"sunlight_correction_enabled\":true,\r\n" + 
				"         \"country_code\":\"CA\",\r\n" + 
				"         \"heat_x2_delivery\":\"forced-air\",\r\n" + 
				"         \"target_humidity\":35.0,\r\n" + 
				"         \"gear_threshold_low\":0.0,\r\n" + 
				"         \"lower_safety_temp\":4.444,\r\n" + 
				"         \"cooling_x2_source\":\"electric\",\r\n" + 
				"         \"equipment_type\":\"electric\",\r\n" + 
				"         \"heat_pump_aux_threshold\":10.0,\r\n" + 
				"         \"alt_heat_x2_delivery\":\"forced-air\",\r\n" + 
				"         \"heat_pump_comp_threshold\":-31.5,\r\n" + 
				"         \"learning_days_completed_cool\":1,\r\n" + 
				"         \"backplate_bsl_version\":\"2.1\",\r\n" + 
				"         \"current_schedule_mode\":\"HEAT\",\r\n" + 
				"         \"fan_duty_end_time\":0,\r\n" + 
				"         \"hvac_wires\":\"Heat,Cool,Fan,Rh\",\r\n" + 
				"         \"leaf\":false,\r\n" + 
				"         \"type\":\"TBD\",\r\n" + 
				"         \"pin_g_description\":\"fan\",\r\n" + 
				"         \"click_sound\":\"on\",\r\n" + 
				"         \"aux_heat_delivery\":\"forced-air\",\r\n" + 
				"         \"away_temperature_low_enabled\":true,\r\n" + 
				"         \"filter_changed_date\":0,\r\n" + 
				"         \"heat_pump_comp_threshold_enabled\":false,\r\n" + 
				"         \"preconditioning_ready\":true,\r\n" + 
				"         \"has_dehumidifier\":false,\r\n" + 
				"         \"fan_cooling_enabled\":true,\r\n" + 
				"         \"leaf_away_high\":28.88,\r\n" + 
				"         \"fan_cooling_readiness\":\"not ready\",\r\n" + 
				"         \"temperature_scale\":\"C\",\r\n" + 
				"         \"device_locale\":\"en_US\",\r\n" + 
				"         \"maint_band_upper\":0.39,\r\n" + 
				"         \"error_code\":\"\",\r\n" + 
				"         \"battery_level\":3.846,\r\n" + 
				"         \"preconditioning_active\":false,\r\n" + 
				"         \"fan_control_state\":false,\r\n" + 
				"         \"away_temperature_high_enabled\":true,\r\n" + 
				"         \"learning_days_completed_heat\":3,\r\n" + 
				"         \"upper_safety_temp_enabled\":false,\r\n" + 
				"         \"pin_star_description\":\"none\",\r\n" + 
				"         \"preconditioning_enabled\":false,\r\n" + 
				"         \"current_humidity\":34,\r\n" + 
				"         \"dual_fuel_breakpoint\":-1.0,\r\n" + 
				"         \"postal_code\":\"N5Y5M4\",\r\n" + 
				"         \"backplate_mono_version\":\"4.0.14\",\r\n" + 
				"         \"alt_heat_source\":\"gas\",\r\n" + 
				"         \"aux_lockout_leaf\":10.0,\r\n" + 
				"         \"has_heat_pump\":false,\r\n" + 
				"         \"heater_delivery\":\"forced-air\",\r\n" + 
				"         \"radiant_control_enabled\":false,\r\n" + 
				"         \"auto_away_reset\":false,\r\n" + 
				"         \"away_temperature_low\":10.0,\r\n" + 
				"         \"has_air_filter\":true,\r\n" + 
				"         \"temperature_lock\":false,\r\n" + 
				"         \"upper_safety_temp\":35.0,\r\n" + 
				"         \"time_to_target_training\":\"training\",\r\n" + 
				"         \"dehumidifier_type\":\"unknown\",\r\n" + 
				"         \"fan_timer_duration\":900,\r\n" + 
				"         \"target_time_confidence\":0.0,\r\n" + 
				"         \"temperature_lock_low_temp\":20.0,\r\n" + 
				"         \"pin_w1_description\":\"heat\",\r\n" + 
				"         \"forced_air\":true,\r\n" + 
				"         \"temperature_lock_pin_hash\":\"\",\r\n" + 
				"         \"auto_dehum_enabled\":false,\r\n" + 
				"         \"leaf_type\":1,\r\n" + 
				"         \"backplate_mono_info\":\"TFE (BP_D2) 4.0.14 (root@bamboo) 2013-04-16 17:44:31\",\r\n" + 
				"         \"star_type\":\"unknown\",\r\n" + 
				"         \"has_dual_fuel\":false,\r\n" + 
				"         \"maint_band_lower\":0.39,\r\n" + 
				"         \"creation_time\":1368368282965,\r\n" + 
				"         \"learning_time\":1020,\r\n" + 
				"         \"has_humidifier\":false,\r\n" + 
				"         \"learning_days_completed_range\":0,\r\n" + 
				"         \"dehumidifier_orientation_selected\":\"unknown\",\r\n" + 
				"         \"leaf_schedule_delta\":1.11,\r\n" + 
				"         \"logging_priority\":\"informational\",\r\n" + 
				"         \"user_brightness\":\"high\",\r\n" + 
				"         \"leaf_away_low\":16.67,\r\n" + 
				"         \"pin_rc_description\":\"none\",\r\n" + 
				"         \"auto_dehum_state\":false,\r\n" + 
				"         \"serial_number\":\"02AA01AB501208GY\",\r\n" + 
				"         \"heat_x2_source\":\"gas\",\r\n" + 
				"         \"mac_address\":\"18b4300a5196\",\r\n" + 
				"         \"fan_duty_start_time\":0,\r\n" + 
				"         \"time_to_target\":0,\r\n" + 
				"         \"backplate_model\":\"Backplate-2.5\",\r\n" + 
				"         \"model_version\":\"Display-2.6\",\r\n" + 
				"         \"heat_pump_aux_threshold_enabled\":true,\r\n" + 
				"         \"ob_persistence\":true\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"shared\":{\r\n" + 
				"      \"02AA01AB501208GY\":{\r\n" + 
				"         \"$version\":62932194,\r\n" + 
				"         \"$timestamp\":1368390402000,\r\n" + 
				"         \"touched_by\":{\r\n" + 
				"\r\n" + 
				"         },\r\n" + 
				"         \"auto_away\":0,\r\n" + 
				"         \"auto_away_learning\":\"training\",\r\n" + 
				"         \"hvac_heat_x3_state\":false,\r\n" + 
				"         \"compressor_lockout_enabled\":false,\r\n" + 
				"         \"hvac_alt_heat_state\":false,\r\n" + 
				"         \"target_temperature_type\":\"heat\",\r\n" + 
				"         \"hvac_heater_state\":false,\r\n" + 
				"         \"hvac_emer_heat_state\":false,\r\n" + 
				"         \"can_heat\":true,\r\n" + 
				"         \"compressor_lockout_timeout\":0,\r\n" + 
				"         \"hvac_cool_x2_state\":false,\r\n" + 
				"         \"target_temperature_high\":24.0,\r\n" + 
				"         \"hvac_aux_heater_state\":false,\r\n" + 
				"         \"hvac_heat_x2_state\":false,\r\n" + 
				"         \"target_temperature_low\":20.0,\r\n" + 
				"         \"target_temperature\":22,\r\n" + 
				"         \"hvac_ac_state\":false,\r\n" + 
				"         \"hvac_fan_state\":false,\r\n" + 
				"         \"target_change_pending\":false,\r\n" + 
				"         \"name\":\"Main\",\r\n" + 
				"         \"current_temperature\":22.47,\r\n" + 
				"         \"hvac_alt_heat_x2_state\":false,\r\n" + 
				"         \"can_cool\":true\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"schedule\":{\r\n" + 
				"      \"02AA01AB501208GY\":{\r\n" + 
				"         \"$version\":1930634632,\r\n" + 
				"         \"$timestamp\":1368378414000,\r\n" + 
				"         \"days\":{\r\n" + 
				"            \"3\":{\r\n" + 
				"               \"0\":{\r\n" + 
				"                  \"touched_by\":1,\r\n" + 
				"                  \"time\":0,\r\n" + 
				"                  \"touched_tzo\":-14400,\r\n" + 
				"                  \"entry_type\":\"continuation\",\r\n" + 
				"                  \"temp\":20.0,\r\n" + 
				"                  \"type\":\"HEAT\",\r\n" + 
				"                  \"touched_at\":1368371820\r\n" + 
				"               }\r\n" + 
				"            },\r\n" + 
				"            \"2\":{\r\n" + 
				"               \"0\":{\r\n" + 
				"                  \"touched_by\":1,\r\n" + 
				"                  \"time\":0,\r\n" + 
				"                  \"touched_tzo\":-14400,\r\n" + 
				"                  \"entry_type\":\"continuation\",\r\n" + 
				"                  \"temp\":20.0,\r\n" + 
				"                  \"type\":\"HEAT\",\r\n" + 
				"                  \"touched_at\":1368371820\r\n" + 
				"               }\r\n" + 
				"            },\r\n" + 
				"            \"1\":{\r\n" + 
				"               \"0\":{\r\n" + 
				"                  \"touched_by\":1,\r\n" + 
				"                  \"time\":0,\r\n" + 
				"                  \"touched_tzo\":-14400,\r\n" + 
				"                  \"entry_type\":\"continuation\",\r\n" + 
				"                  \"temp\":20.0,\r\n" + 
				"                  \"type\":\"HEAT\",\r\n" + 
				"                  \"touched_at\":1368371820\r\n" + 
				"               }\r\n" + 
				"            },\r\n" + 
				"            \"0\":{\r\n" + 
				"               \"0\":{\r\n" + 
				"                  \"touched_by\":1,\r\n" + 
				"                  \"time\":0,\r\n" + 
				"                  \"touched_tzo\":-14400,\r\n" + 
				"                  \"entry_type\":\"continuation\",\r\n" + 
				"                  \"temp\":20.0,\r\n" + 
				"                  \"type\":\"HEAT\",\r\n" + 
				"                  \"touched_at\":1368371820\r\n" + 
				"               }\r\n" + 
				"            },\r\n" + 
				"            \"6\":{\r\n" + 
				"               \"0\":{\r\n" + 
				"                  \"touched_by\":1,\r\n" + 
				"                  \"time\":0,\r\n" + 
				"                  \"touched_tzo\":-14400,\r\n" + 
				"                  \"entry_type\":\"continuation\",\r\n" + 
				"                  \"temp\":20.0,\r\n" + 
				"                  \"type\":\"HEAT\",\r\n" + 
				"                  \"touched_at\":1368371820\r\n" + 
				"               }\r\n" + 
				"            },\r\n" + 
				"            \"5\":{\r\n" + 
				"               \"0\":{\r\n" + 
				"                  \"touched_by\":1,\r\n" + 
				"                  \"time\":0,\r\n" + 
				"                  \"touched_tzo\":-14400,\r\n" + 
				"                  \"entry_type\":\"continuation\",\r\n" + 
				"                  \"temp\":20.0,\r\n" + 
				"                  \"type\":\"HEAT\",\r\n" + 
				"                  \"touched_at\":1368371820\r\n" + 
				"               }\r\n" + 
				"            },\r\n" + 
				"            \"4\":{\r\n" + 
				"               \"0\":{\r\n" + 
				"                  \"touched_by\":1,\r\n" + 
				"                  \"time\":0,\r\n" + 
				"                  \"touched_tzo\":-14400,\r\n" + 
				"                  \"entry_type\":\"continuation\",\r\n" + 
				"                  \"temp\":20.0,\r\n" + 
				"                  \"type\":\"HEAT\",\r\n" + 
				"                  \"touched_at\":1368371820\r\n" + 
				"               }\r\n" + 
				"            }\r\n" + 
				"         },\r\n" + 
				"         \"schedule_mode\":\"HEAT\",\r\n" + 
				"         \"name\":\"Main Current Schedule\",\r\n" + 
				"         \"ver\":2\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"user_alert_dialog\":{\r\n" + 
				"      \"323260\":{\r\n" + 
				"         \"$version\":-615481805,\r\n" + 
				"         \"$timestamp\":1368371413000,\r\n" + 
				"         \"dialog_id\":\"confirm-pairing\",\r\n" + 
				"         \"dialog_data\":\"\"\r\n" + 
				"      }\r\n" + 
				"   },\r\n" + 
				"   \"user\":{\r\n" + 
				"      \"323260\":{\r\n" + 
				"         \"$version\":878705010,\r\n" + 
				"         \"$timestamp\":1368143955000,\r\n" + 
				"         \"name\":\"sean.stuckless@gmail.com\",\r\n" + 
				"         \"structures\":[\r\n" + 
				"            \"structure.73f6fb70-b904-11e2-acbb-12313b0cf507\"\r\n" + 
				"         ]\r\n" + 
				"      }\r\n" + 
				"   }\r\n" + 
				"}").getAsJsonObject();
	}
}
